// Code generated by cmd/reset. DO NOT EDIT.

package models

// Reset приводит поля Metrics к начальному состоянию.
func (v *Metrics) Reset() {
	if v == nil {
		return
	}
	v.ID = ""
	v.MType = ""
	if v.Delta != nil {
		(*v.Delta) = 0
	}
	if v.Value != nil {
		(*v.Value) = 0
	}
	v.Hash = ""
}
