package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func generate(t *testing.T, source string) string {
	t.Helper()

	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "types.go"), []byte(source), 0644))
	require.NoError(t, run(dir))

	data, err := os.ReadFile(filepath.Join(dir, generatedFile))
	require.NoError(t, err)

	return string(data)
}

func TestGeneratesForMarkedStructOnly(t *testing.T) {
	out := generate(t, `package sample

// generate:reset
type Marked struct {
	value int
}

type Skipped struct {
	value int
}
`)

	assert.Contains(t, out, "func (v *Marked) Reset()")
	assert.NotContains(t, out, "Skipped", "непомеченная структура пропускается")
	assert.Contains(t, out, "// Code generated by cmd/reset. DO NOT EDIT.")
}

func TestResetsPrimitives(t *testing.T) {
	out := generate(t, `package sample

// generate:reset
type Values struct {
	number  int
	decimal float64
	text    string
	flag    bool
}
`)

	assert.Contains(t, out, "v.number = 0")
	assert.Contains(t, out, "v.decimal = 0")
	assert.Contains(t, out, `v.text = ""`)
	assert.Contains(t, out, "v.flag = false")
}

func TestResetsSlicesAndMaps(t *testing.T) {
	out := generate(t, `package sample

// generate:reset
type Collections struct {
	items []string
	index map[string]int
}
`)

	assert.Contains(t, out, "v.items = v.items[:0]", "слайс обрезается, но не зануляется")
	assert.Contains(t, out, "clear(v.index)")
}

func TestResetsPointers(t *testing.T) {
	out := generate(t, `package sample

// generate:reset
type Pointers struct {
	text *string
}
`)

	assert.Contains(t, out, "if v.text != nil {")
	assert.Contains(t, out, `(*v.text) = ""`)
}

func TestCallsNestedReset(t *testing.T) {
	out := generate(t, `package sample

// generate:reset
type Outer struct {
	inner Inner
}

type Inner struct {
	value int
}
`)

	assert.Contains(t, out, "interface{ Reset() }", "для вложенной структуры вызывается её Reset")
	assert.Contains(t, out, "resetter.Reset()")
}

func TestSkipsPackageWithoutMarks(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "types.go"), []byte("package sample\n\ntype Plain struct{}\n"), 0644))
	require.NoError(t, run(dir))

	_, err := os.Stat(filepath.Join(dir, generatedFile))
	assert.True(t, os.IsNotExist(err), "без помеченных структур файл не создаётся")
}

func TestScansNestedDirectories(t *testing.T) {
	dir := t.TempDir()
	nested := filepath.Join(dir, "internal", "deep")
	require.NoError(t, os.MkdirAll(nested, 0755))
	require.NoError(t, os.WriteFile(filepath.Join(nested, "types.go"), []byte(`package deep

// generate:reset
type Nested struct {
	value int
}
`), 0644))

	require.NoError(t, run(dir))

	data, err := os.ReadFile(filepath.Join(nested, generatedFile))
	require.NoError(t, err)
	assert.Contains(t, string(data), "func (v *Nested) Reset()")
}

func TestGeneratedCodeIsFormatted(t *testing.T) {
	out := generate(t, `package sample

// generate:reset
type Values struct {
	number int
}
`)

	assert.False(t, strings.Contains(out, "\t\t\t\t"), "код проходит через format.Source")
}
