// Code generated by cmd/reset. DO NOT EDIT.

package audit

// Reset приводит поля Event к начальному состоянию.
func (v *Event) Reset() {
	if v == nil {
		return
	}
	v.IPAddress = ""
	v.Metrics = v.Metrics[:0]
	v.Timestamp = 0
}
